import {InMemoryDbService} from 'angular-in-memory-web-api';

export class InMemoryData implements InMemoryDbService {
  createDb() {
    const persons = [
      {id: 1, firstname: 'Zewdu', lastname: 'Negatu', email: 'negatu@gmx.com'},
      {id: 2, firstname: 'Isabella', lastname: 'Robinson', email: 'isabella@robinson.net'},
      {id: 3, firstname: 'Zhang ', lastname: 'Wei', email: 'zhang@wei.com'},
      {id: 4, firstname: 'Alice', lastname: 'Thompson', email: 'alice@thompson.co.uk'},
      {id: 5, firstname: 'Ethan', lastname: 'White', email: 'ethan@white.co.uk'},
      {id: 6, firstname: 'Ella', lastname: 'Watson', email: 'ella@watson.com'},
      {id: 7, firstname: 'Henry', lastname: 'Jackson', email: 'henry@jackson.com'},
      {id: 8, firstname: 'Emily', lastname: 'Wilson', email: 'emily@wilson.net'},
      {id: 9, firstname: 'Jack', lastname: 'Young', email: 'jack@young.com'},
      {id: 10, firstname: 'Mia', lastname: 'Write', email: 'mia@write.com'},
      {id: 11, firstname: 'Rahul', lastname: 'Acharya', email: 'raul@acharya.net'},
      {id: 12, firstname: 'Chloe', lastname: 'Harris', email: 'chloe@harris.com'},
      {id: 13, firstname: 'Oliver', lastname: 'Smith', email: 'oliver@smith.co.uk'},
      {id: 14, firstname: 'Olivia', lastname: 'Jones', email: 'olivia@jones.com'},
      {id: 15, firstname: 'Jacob', lastname: 'Walker', email: 'jacob@walker.com'},
      {id: 16, firstname: 'Lily', lastname: 'Williams', email: 'lily@williams.com'},
      {id: 17, firstname: 'Samuel', lastname: 'Abimbola.', email: 'samuel@abimola.com'},
      {id: 18, firstname: 'Sophia', lastname: 'Davies', email: 'sophia@davies.co.uk'},
      {id: 19, firstname: 'Harry', lastname: 'Evans', email: 'harry@evans.gov'},
      {id: 20, firstname: 'Emily', lastname: 'Kelly', email: 'emily@kelly.com'},
      {id: 21, firstname: 'Jack', lastname: 'Roberts', email: 'jack@Roberts.org'},
      {id: 22, firstname: 'Aisha', lastname: 'Abashi', email: 'aisha@abashi.com'},
      {id: 23, firstname: 'Charlie', lastname: 'Johnson', email: 'charlie@johnson.com'},
      {id: 24, firstname: 'Neha', lastname: 'Khatri', email: 'neha@khatri.com'},
      {id: 25, firstname: 'Joshua', lastname: 'Robinson', email: 'joshua@robinson.com'},
      {id: 26, firstname: 'Priya', lastname: 'Agarwal', email: 'priya@agarwal.com'},
      {id: 27, firstname: 'Freddie', lastname: 'Thompson', email: 'freddie@thompson.org'},
      {id: 28, firstname: 'Charlotte', lastname: 'Watson', email: 'charlotte@watson.com'},
      {id: 29, firstname: 'Leo', lastname: 'Jackson', email: 'leo@jackson.com'},
      {id: 30, firstname: 'Poppy', lastname: 'Griffiths', email: 'poppy@griffiths.com'},
      {id: 31, firstname: 'Jacob', lastname: 'Miller', email: 'jacob@miller.com'},
      {id: 32, firstname: 'Isabella', lastname: 'Wood', email: 'isabella@Wood.com'},
      {id: 33, firstname: 'George', lastname: 'Bailey', email: 'george@bailey.gov'},
      {id: 34, firstname: 'Alice', lastname: 'Cooper', email: 'alice@cooper.com'},
      {id: 35, firstname: 'Ethan', lastname: 'Price', email: 'ethan@price.com'},
      {id: 36, firstname: 'Li', lastname: 'Na', email: 'li@na.com'},
      {id: 37, firstname: 'Henry', lastname: 'Wilson', email: 'henry@Wilson.net'},
      {id: 38, firstname: 'Emily', lastname: 'Write', email: 'emily@write.com'},
      {id: 39, firstname: 'Jack', lastname: 'Thomas', email: 'jack@thomas.co.uk'},
      {id: 40, firstname: 'Mia', lastname: 'Green', email: 'mia@green.com'},
      {id: 41, firstname: 'Oscar', lastname: 'Harris', email: 'oscar@Harris.org'},
      {id: 42, firstname: 'Chloe', lastname: 'Smith', email: 'chloe@Smith.com'},
      {id: 43, firstname: 'Oliver', lastname: 'Jones', email: 'oliver@Jones.com'},
      {id: 44, firstname: 'Blessing', lastname: 'Adebisi.', email: 'blessing@adebisi.net'},
      {id: 45, firstname: 'Muhammad', lastname: 'Ali', email: 'muhammad@ali.co.uk'},
      {id: 46, firstname: 'Lily', lastname: 'Brown', email: 'lily@Brown.com'},
      {id: 47, firstname: 'Raj', lastname: 'Ahuja', email: 'raj@Ahuja.com'},
      {id: 48, firstname: 'Sophia', lastname: 'Evans', email: 'sophia@Evans.com'},
      {id: 49, firstname: 'Harry', lastname: 'Bell', email: 'harry@bell.com'},
      {id: 50, firstname: 'Emily', lastname: 'Lawrence', email: 'emily@lawrence.gov'},
    ];
    return {persons};
  }
}
